---

app:
  run_env: ""
  http_port: ""
  log_file: logs/admin.log

mysql:
  db: mysql
  db_host: 10.211.55.6
  db_port: 3306
  db_user: root
  db_password: hnh666666
  db_name: ips

redis:
  db: 0
  host: 10.211.55.6
  port: 6379
  password: ""


